# nixpacks.toml

[phases.build]
# Сборка фронтенда на уже установленных зависимостях (root npm ci делает Nixpacks)
cmds = ["cd frontend && npm run build"]

[start]
# Миграции + запуск сервера
cmd = "cd server && npx sequelize-cli db:migrate && npm start"
