# nixpacks.toml

[phases.build]
# Устанавливаем зависимости именно для нашего сервера
cmds = ["cd server && npm install"]

[start]
# Запускаем миграции и стартуем сервер
cmd = "cd server && npx sequelize-cli db:migrate && npm start"