# nixpacks.toml

[phases.build]
# Устанавливаем все зависимости и собираем фронтенд
cmds = ["npm install --legacy-peer-deps", "npm run build"]

[start]
# Выводим значения ключевых переменных БД для отладки
cmd = "node -e \"console.log(`MYSQLHOST='${process.env.MYSQLHOST}'`); console.log(`MYSQLPORT='${process.env.MYSQLPORT}'`); console.log(`MYSQLUSER='${process.env.MYSQLUSER}'`);\""