# nixpacks.toml

[phases.build]
# Устанавливаем все зависимости и собираем фронтенд
cmds = ["npm install --legacy-peer-deps", "npm run build"]

[start]
# Запускаем миграции и стартуем сервер
cmd = "cd server && npx sequelize-cli db:migrate && npm start"