# nixpacks.toml

[phases.build]
# Пропускаем шаг сборки, все будет на этапе запуска
cmds = ["echo 'Build step skipped, installing at runtime'"]

[start]
# Установка, миграция и запуск - все в одной команде для надежности
cmd = "cd server && npm install && npx sequelize-cli db:migrate && npm start"