# nixpacks.toml

[phases.build]
# Устанавливаем зависимости именно для нашего сервера
cmds = ["cd server && npm install"]

[start]
# Запускаем ТОЛЬКО сервер для проверки
cmd = "cd server && npm start"