# nixpacks.toml

[phases.build]
# Устанавливаем зависимости на этапе сборки
cmds = ["cd server && npm ci --production"]

[start]
# Только миграции и запуск
cmd = "cd server && npx sequelize-cli db:migrate && npm start"
