# nixpacks.toml

[phases.build]
# Устанавливаем зависимости для сервера
cmds = ["cd server && npm install"]

[start]
# Запускаем миграции напрямую и стартуем сервер
cmd = "cd server && ./node_modules/.bin/sequelize-cli db:migrate && npm start"