[phases.setup]
cmds = [
  "cd frontend && npm install",
  "cd server && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "cd server && npx sequelize-cli db:migrate && npm start"
