[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm run build"

[deploy]
startCommand = "cd server && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"